### ISSUE TITLE
Convert paths to relative

### ISSUE THREAD

**Issue by EMDM45** [arokettu/php-path#1]
Please help me.
I have an array of paths. Paths may be absolute or relative. I need to convert all paths to relative automatically in cycle. How can i do it?

**Comment by arokettu** [comment]
It's a question better suited for the community chat, not the issues tracker, but I just noticed that I haven't posted the link in this project. Here it is: https://gitter.im/arokettu/community

As for the question itself, I guess something like that:

```php
<?php

declare(strict_types=1);

use Arokettu\Path\AbsolutePathInterface;
use Arokettu\Path\PathFactory;

$paths = [
    '/home/sandfox',
    '/etc/php',
    '../root',
    'test/test/test',
];

$basePath = '/etc';

$bpObj = PathFactory::parse($basePath);

foreach ($paths as &$path) {
    $obj = PathFactory::parse($path);

    if ($obj instanceof AbsolutePathInterface) {
        $path = $bpObj->makeRelative($obj)->toString();
    }
}

//array(4) {
//    [0] =>
//  string(15) "../home/sandfox"
//    [1] =>
//  string(3) "php"
//    [2] =>
//  string(7) "../root"
//    [3] =>
//  string(14) "test/test/test"
//}
var_dump($paths);
```

Please ask further questions in the community chat
